apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
  name: argocd-server
  namespace: argocd
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
  - name: https
    port: 8081
    protocol: TCP
  selector:
    app.kubernetes.io/name: argocd-server
  type: LoadBalancer