apiVersion: v1
data:
  admin.password: JDJ5JDEwJEdvRlFyTkpyYnNMQUFvRzVxci9FUU9paGo0MDQyT1I5TVJzMnBZcUVPL1ZCRnAxOXQ1cy4y
  admin.passwordMtime: MjAyMi0wOC0xNlQxMzoxNzowMENFU1Q=
  server.secretkey: S3ViYnRTUnlCNUJNeGc3eWgzak1iOWprNXFmWnpYUERnTzl4bzR5em9OMD0=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque