apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
  name: ArgoCD
- cluster:
  name: dev

users:
- name: dev

contexts:
- context:
  name: dev-frontend
- context:
  name: dev-storage
- context:
  name: exp-scratch